### ISSUE TITLE
How to create realtime database using firebase

### ISSUE THREAD

**Issue by ishafayshahid** [makkhay/CTube#1]
He there, I'm unable to add video to favourite list. Can someone help me out to create real time database in firebase.
<img width="962" alt="database" src="https://user-images.githubusercontent.com/24617477/77886060-d18b3700-7285-11ea-8c84-805f0fd7c00c.png">

**Comment by makkhay** [comment]
what have you tried so far? You need to set up your firebase project and make sure you have enabled write and read access.
